name: win-ca-smoke

permissions:
  contents: read

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  smoke:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install project dependencies
        shell: pwsh
        run: uv sync --dev

      - name: Create local root CA and server cert (untrusted)
        shell: pwsh
        run: ./scripts/win/create-local-ca.ps1 -PfxPath servercert.pfx -PfxPassword 'pass' -NoTrust

      - name: HTTPS smoke fails before trust
        id: pre_smoke
        continue-on-error: true
        shell: pwsh
        env:
          NODE_EXTRA_CA_CERTS: ${{ github.workspace }}\root.pem
          WIN_CA_SMOKE: '1'
        run: |
          $job = Start-Job -ScriptBlock { node scripts/https-server.mjs }
          try {
            $deadline = (Get-Date).AddSeconds(30)
            do {
              $ready = Test-NetConnection -ComputerName 127.0.0.1 -Port 4443 -WarningAction SilentlyContinue -InformationLevel Quiet
              if (-not $ready) { Start-Sleep -Milliseconds 200 }
            } while (-not $ready -and (Get-Date) -lt $deadline)
            if (-not $ready) { throw 'HTTPS server did not become ready in time' }
            uv run pytest tests/test_win_ca_smoke.py --maxfail=1 --disable-warnings -q
          } finally {
            Stop-Job -Job $job -PassThru | Remove-Job
          }

      - name: Assert failure without trusted root
        if: steps.pre_smoke.outcome != 'failure'
        shell: pwsh
        run: |
          Write-Host 'Expected win_ca_smoke to fail before trusting root CA'
          exit 1

      - name: Create and trust local root CA and server cert
        shell: pwsh
        run: ./scripts/win/create-local-ca.ps1 -PfxPath servercert.pfx -PfxPassword 'pass'

      - name: HTTPS smoke (start server and run pytest)
        shell: pwsh
        env:
          NODE_EXTRA_CA_CERTS: ${{ github.workspace }}\root.pem
          WIN_CA_SMOKE: '1'
        run: |
          $job = Start-Job -ScriptBlock { node scripts/https-server.mjs }
          try {
            $deadline = (Get-Date).AddSeconds(30)
            do {
              $ready = Test-NetConnection -ComputerName 127.0.0.1 -Port 4443 -WarningAction SilentlyContinue -InformationLevel Quiet
              if (-not $ready) { Start-Sleep -Milliseconds 200 }
            } while (-not $ready -and (Get-Date) -lt $deadline)
            if (-not $ready) { throw 'HTTPS server did not become ready in time' }
            uv run pytest tests/test_win_ca_smoke.py --maxfail=1 --disable-warnings -q
          } finally {
            Stop-Job -Job $job -PassThru | Remove-Job
          }

      - name: Cleanup local certs
        if: always()
        shell: pwsh
        run: |
          try {
            Get-ChildItem -Path Cert:\CurrentUser\Root | Where-Object { $_.Subject -eq 'CN=KittyCAD-Test-Root' } | Remove-Item -Force -ErrorAction SilentlyContinue
            Get-ChildItem -Path Cert:\CurrentUser\My | Where-Object { $_.Subject -match 'CN=KittyCAD-Test-Root|CN=localhost' } | Remove-Item -Force -ErrorAction SilentlyContinue
          } catch {}
          try {
            Get-ChildItem -Path Cert:\LocalMachine\Root | Where-Object { $_.Subject -eq 'CN=KittyCAD-Test-Root' } | Remove-Item -Force -ErrorAction SilentlyContinue
            Get-ChildItem -Path Cert:\LocalMachine\My | Where-Object { $_.Subject -match 'CN=KittyCAD-Test-Root|CN=localhost' } | Remove-Item -Force -ErrorAction SilentlyContinue
          } catch {}
          Remove-Item -Path servercert.pfx,root.pem,root.cer -Force -ErrorAction SilentlyContinue
